apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-python
    app.kubernetes.io/part-of: e2e-multiple-components
  name: component-python
  namespace: e2e-demo-beal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: component-python
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: component-python
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:1ec71106b64849599b4ead07a9d776f3
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
