apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-python
    app.kubernetes.io/part-of: e2e-multiple-components
  name: component-python
  namespace: e2e-demo-beal
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: component-python
    weight: 100
status: {}
