apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: e2e-multiple-components
    appstudio.openshift.io/component: component-python
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: component-python
  namespace: e2e-demo-beal
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_redhat-appstudio-qe_devfile-sample-python-basic
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/redhat-appstudio-qe/devfile-sample-python-basic
